name: SSH

on:
  schedule:
    - cron: '0 */6 * * *' # This will run the workflow every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Other steps

      - name: Run script
        run: |
          curl -sSf https://sshx.io/get | sh -s run
